### ISSUE TITLE
map does not render if it is inside a tabbed panel

### ISSUE THREAD

**Issue by vesper8** [mostafaznv/nova-map-field#9]
I'm using your map fields in combination with https://github.com/eminiarts/nova-tabs.

The maps are not in the "main" tab and I've noticed that if the page loads and the map is not immediately available, then when switching to the tab that contains the tab, some elements will be visible such as the zoom control icons, but the map itself will not render.

If you refresh the page while on the correct tab then the map renders normally.

I know this may be out of scope but I was wondering if you might know what's going on here and how to work around it maybe?

And one more thing, I don't want to spam your issues with so many posts but.. I've noticed that your maps cannot be panned? They are fully static, and can only be zoomed. Is this intended? It would be nice to be able to pan it.

Many thanks!

**Comment by mostafaznv** [comment]
Hi again.
Thanks for reporting this.

This is a `vue3-openlayers` bug and I reported it.
https://github.com/MelihAltintas/vue3-openlayers/issues/91

I don't close this issue because I'm waiting for a reply from maintainers of `vue3-openlayers`

----

And about the last question.
Maps are static in detail pages now. 
I will change this behavior in future versions. thank for reporting this.

**Comment by mostafaznv** [comment]
Please update the package to [1.5.0](https://github.com/mostafaznv/nova-map-field/releases/tag/1.5.0)

Your second question have been resolved.

**Comment by mostafaznv** [comment]
the issue with tabs fixed and you can use it in the next release

**Comment by mostafaznv** [comment]
released under [v3.1.0](https://github.com/mostafaznv/nova-map-field/releases/tag/3.1.0)
